branch-defaults:
  default:
    environment: Rails1-env
  master:
    environment: Rails1-env
environment-defaults:
  Rails1-env:
    branch: master
    #repository: Rails
global:
  application_name: Rails1
  default_ec2_keyname: frankfurtkeypair
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Puma with Ruby
    2.6 running on 64bit Amazon Linux/2.9.0
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
